# Generated by Django 5.2.8 on 2025-11-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_question_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='core.tag', verbose_name='Теги'),
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('answer', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('question', 'author')},
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('correct', True)), fields=('correct', 'question'), name='unique_correct_question_answer'),
        ),
    ]
