# Generated by Django 5.2.8 on 2025-11-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='modyfied_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='modyfied_at',
            new_name='modified_at',
        ),
    ]
