# Generated by Django 5.2.8 on 2025-11-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_modyfied_at_answer_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='mark',
            field=models.SmallIntegerField(choices=[(-1, 'downvote'), (0, 'novote'), (1, 'upvote')], default=0),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='mark',
            field=models.SmallIntegerField(choices=[(-1, 'downvote'), (0, 'novote'), (1, 'upvote')], default=0),
        ),
    ]
