# Generated by Django 5.2.8 on 2025-11-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
