# Generated by Django 5.2.8 on 2025-11-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_answer_text_alter_question_text'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('question', 'author'), name='unique_question_author'),
        ),
    ]
