# Generated by Django 5.2.8 on 2025-11-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_answer_unique_question_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerlike',
            options={'verbose_name': 'AnswerLike', 'verbose_name_plural': 'AnswerLikes'},
        ),
        migrations.AlterModelOptions(
            name='questionlike',
            options={'verbose_name': 'QuestionLike', 'verbose_name_plural': 'QuestionLikes'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tag',
        ),
    ]
