# Generated by Django 5.2.8 on 2025-11-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_answerlike_options_alter_questionlike_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='questionCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
