# Generated by Django 5.2.8 on 2025-11-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tag_questioncount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
