# Generated by Django 5.2.8 on 2026-01-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(default='emprty'),
            preserve_default=False,
        ),
    ]
