# Generated by Django 5.2.8 on 2026-01-20 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlike',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='core.question', verbose_name='Question'),
        ),
    ]
