# Generated by Django 5.2.8 on 2026-01-20 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_questionlike_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='likes',
            new_name='likes_count',
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.question', verbose_name='Question'),
        ),
    ]
