# Generated by Django 5.2.8 on 2026-01-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_likes_question_likes_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='likes',
            new_name='likes_count',
        ),
    ]
